// GENERATED CODE - Placeholder for drift's generated code
// Run: flutter pub run build_runner build

part of 'database.dart';

// This file will be generated by build_runner
// The actual implementation will be created when you run:
// flutter pub run build_runner build
